#!/usr/bin/env node
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

/**
 * Make `gradlew assembleRelease` produce a *signed*, installable APK.
 *
 * React Native's generated project signs release builds with the debug key.
 * That APK installs, but every machine's debug key is different, so the next
 * build from another laptop cannot update it — Android refuses an update whose
 * signature changed. For something you hand to real testers that is a trap, so
 * this creates one stable release key and wires it in.
 *
 * The keystore lives OUTSIDE the repo, in ~/.keys/<slug>/. It is the one file
 * that must never be committed and must never be lost: lose it and the only way
 * to ship an update is a new listing under a new package name.
 *
 * Run after `expo prebuild`, which regenerates android/ and undoes the patch.
 */

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const ANDROID = path.join(ROOT, 'android');

const app = JSON.parse(fs.readFileSync(path.join(ROOT, 'app.json'), 'utf8'));
const SLUG = app.expo.slug || 'app';

const KEY_DIR = path.join(os.homedir(), '.keys', SLUG);
const KEYSTORE = path.join(KEY_DIR, 'release.keystore');
const CREDS = path.join(KEY_DIR, 'credentials.json');
const ALIAS = 'release';

function say(msg) { console.log(`  ${msg}`); }

/** Create the keystore once, and remember its passwords beside it. */
function ensureKeystore() {
  if (fs.existsSync(KEYSTORE) && fs.existsSync(CREDS)) {
    const creds = JSON.parse(fs.readFileSync(CREDS, 'utf8'));
    say(`signing key: ${KEYSTORE} (existing)`);
    return creds;
  }

  fs.mkdirSync(KEY_DIR, { recursive: true });

  // Generated, not chosen. A password someone picks for a build script is a
  // password that ends up in chat; this one only ever exists in a file next to
  // the key it protects, which is already the thing being guarded.
  const password = crypto.randomBytes(24).toString('base64url');

  say('no signing key yet — creating one');
  execFileSync('keytool', [
    '-genkeypair', '-v',
    '-keystore', KEYSTORE,
    '-alias', ALIAS,
    '-keyalg', 'RSA',
    '-keysize', '2048',
    // 10000 days. Play requires a key valid past 2033; a short-lived key means
    // being locked out of your own app on an arbitrary future date.
    '-validity', '10000',
    '-storepass', password,
    '-keypass', password,
    '-dname', `CN=${app.expo.name || SLUG}, OU=Mobile, O=MyAgeMap, L=Hyderabad, S=Telangana, C=IN`,
  ], { stdio: ['ignore', 'ignore', 'inherit'] });

  const creds = { keystore: KEYSTORE, alias: ALIAS, password };
  fs.writeFileSync(CREDS, `${JSON.stringify(creds, null, 2)}\n`, { mode: 0o600 });

  say(`signing key created: ${KEYSTORE}`);
  say('BACK THIS FOLDER UP. Losing it means you can never update this app.');
  return creds;
}

/** Append the credentials Gradle reads. */
function writeGradleProperties(creds) {
  const file = path.join(ANDROID, 'gradle.properties');
  if (!fs.existsSync(file)) {
    throw new Error(`No ${file}. Run "npx expo prebuild --platform android" first.`);
  }

  let text = fs.readFileSync(file, 'utf8');
  text = text.replace(/\n# --- release signing[\s\S]*?# --- end release signing ---\n/, '\n');

  // Forward slashes: Gradle reads properties as Java strings, where a Windows
  // backslash is an escape and silently mangles the path.
  const storePath = creds.keystore.split(path.sep).join('/');

  text += [
    '',
    '# --- release signing (generated by scripts/ensure-signing.js) ---',
    `RELEASE_STORE_FILE=${storePath}`,
    `RELEASE_KEY_ALIAS=${creds.alias}`,
    `RELEASE_STORE_PASSWORD=${creds.password}`,
    `RELEASE_KEY_PASSWORD=${creds.password}`,
    '# --- end release signing ---',
    '',
  ].join('\n');

  fs.writeFileSync(file, text);
  say('gradle.properties: signing credentials written');
}

/**
 * Point the release build type at the release key instead of the debug one.
 *
 * The generated build.gradle already declares a `debug` signing config and uses
 * it for release. This inserts a `release` config guarded by hasProperty, so a
 * checkout without the credentials still builds (unsigned) rather than failing
 * with a Gradle error nobody can read.
 */
function patchBuildGradle() {
  const file = path.join(ANDROID, 'app', 'build.gradle');
  let text = fs.readFileSync(file, 'utf8');

  if (text.includes('RELEASE_STORE_FILE')) {
    say('build.gradle: already patched');
    return;
  }

  const configBlock = `
        release {
            if (project.hasProperty('RELEASE_STORE_FILE')) {
                storeFile file(RELEASE_STORE_FILE)
                storePassword RELEASE_STORE_PASSWORD
                keyAlias RELEASE_KEY_ALIAS
                keyPassword RELEASE_KEY_PASSWORD
            }
        }
`;

  // Insert into the existing signingConfigs { ... } block, right after it opens.
  const openIdx = text.indexOf('signingConfigs {');
  if (openIdx === -1) throw new Error('No signingConfigs block in android/app/build.gradle');
  const insertAt = text.indexOf('\n', openIdx) + 1;
  text = text.slice(0, insertAt) + configBlock + text.slice(insertAt);

  // Swap the release build type over. The generated file uses the debug config.
  const before = text;
  text = text.replace(
    /(buildTypes\s*\{[\s\S]*?release\s*\{[\s\S]*?signingConfig\s+signingConfigs\.)debug/,
    '$1release',
  );
  if (text === before) {
    throw new Error('Could not repoint the release buildType — build.gradle layout changed.');
  }

  fs.writeFileSync(file, text);
  say('build.gradle: release build type now uses the release key');
}

try {
  const creds = ensureKeystore();
  writeGradleProperties(creds);
  patchBuildGradle();
  console.log('');
} catch (err) {
  console.error(`\n  x signing setup failed: ${err.message}\n`);
  process.exit(1);
}
